# This is a basic workflow to help you get started with Actions

name: Release Extension Development

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths:
    - 'task/*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2.0.0
      with:
        # Repository name with owner. For example, actions/checkout
        repository: Azure/arm-ttk
        path: ttk_files

    - name: run number with offset
      env:
          NUM: ${{ github.run_number }}
      run: |
          echo "offset_build_number=$(($NUM+44))" >> $GITHUB_ENV
    - run: |
          echo "${{env.offset_build_number}}"
    - name: Copy file
      run: |
        rm -r task/arm-ttk/testcases/
        cp -r ttk_files/arm-ttk/testcases/ task/arm-ttk/testcases/       
    - name: Replace Action
      uses: datamonsters/replace-action@v2
      with:
        # Files, comma-separated. Supposed PLACEHOLDER in them
        files: vss-extension.json
        # Comma-separated pairs PLACEHOLDER=value
        replacements: '$buildnumber$=${{env.offset_build_number}}, $taskid$=12e695ee-1e9b-47f2-bc0a-3e4c726b2699, $taskname$=RunARMTTKTestsDev, $taskdisplayname$=Run Azure RM TTK Tests - Dev'
    - name: create package
      run: |
        npx tfx-cli extension create --manifest-globs vss-extension-dev.json
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: extension
        path: Sam-Cogan.ARMTTKExtension-1.0.${{ github.run_number }}-dev.vsix
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: extension
    - name: publish-extension
      run: |
        npx tfx-cli extension publish --vsix extension/Sam-Cogan.ARMTTKExtension-1.0.${{ github.run_number }}-dev.vsix --token ${{secrets.marketplace_pat}}
        
